apiVersion: v1
data:
  config: |
    address-pools:
     - name: default
       protocol: layer2
       addresses:
       - 192.168.0.240-192.168.0.250
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: metallb
    meta.helm.sh/release-namespace: metallb-system
  creationTimestamp: "2020-06-08T03:10:25Z"
  labels:
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metallb
    helm.sh/chart: metallb-0.1.13
  name: metallb
  namespace: metallb-system
  resourceVersion: "20414"
  selfLink: /api/v1/namespaces/metallb-system/configmaps/metallb
  uid: 6e00a9f4-54d6-47aa-99cb-f9138bc7dffc
