---
- hosts: all
  remote_user: manager
  roles:
  - name: cluster
    become: yes
    tags:
      - cluster
      - bootstrap
  - name: certificates
    tags:
      - ca
      - certificate
  - name: mesh
    tags:
      - mesh
  - name: ingress
    tags:
      - ingress
      - proxy
  - name: nas
    tags:
      - nas
  - name: elastic
    tags:
      - elastic
  - name: logging
    tags:
      - logs
      - logging
  - name: vault
    tags:
      - vault
  - name: identity
    tags:
      - identity
      - keycloak
      - iam
  - name: files
    tags:
      - files
  - name: media
    tags:
      - media
  - name: ldap
    tags:
      - ldap
      - directory
  - name: monitoring
    tags:
      - monitoring
  - name: functions
    tags:
      - function
      - functions
      - openfaas
