---
- hosts: all
  remote_user: manager
  roles:
  - name: cluster
    become: yes
    tags:
      - cluster
      - bootstrap
  - name: ingress
    become: no
    tags:
      - ingress
      - lb
  - name: certificates
    tags:
      - ca
      - certificate
  - name: mesh
    tags:
      - mesh
  - name: elastic
    tags:
      - elastic
  - name: nas
    tags:
      - nas
  - name: logging
    tags:
      - logs
      - logging
  - name: vault
    tags:
      - vault
  - name: identity
    tags:
      - identity
      - keycloak
      - iam
