---
- name: init_linkerd
  shell: "/home/{{ ansible_user }}/.linkerd2/bin/linkerd install --identity-external-issuer=true | kubectl apply -f -"
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"