---
- name: Deploy ingress controller
  block:
    - community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: ingress-nginx
    - community.kubernetes.helm:
        chart_ref: ingress-nginx
        name: ingress-nginx
        chart_repo_url: https://kubernetes.github.io/ingress-nginx
        release_namespace: ingress-nginx
        values:
          config.enable-opentracing: "true"
          config.zipkin-collector-host: linkerd-collector.linkerd:55678
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
