---
- name: Ensure workspace folder
  block:
    - file:
        path: terraform
        state: directory
        mode: 0755
    - file:
        path: terraform/ingress
        state: directory
        mode: 0755
- name: Deploy ingress controller
  block:
    - name: Copy files into folder
      copy:
        dest: "terraform/ingress/{{ item }}"
        src: "{{ item }}"
      with_items:
        - ingress.tf
        - terraform.tf
    - stat:
        path: "terraform/ingress/.terraform"
      register: terraform_initialized
    - shell:
        cmd: terraform init
        chdir: "terraform/ingress"
      when: terraform_initialized.stat.exists != true
    - name: Plan Deployment
      terraform:
        project_path: terraform/ingress
        state: planned
        plan_file: plan.out
    - name: Apply Deployment
      terraform:
        project_path: terraform/ingress
        state: present
        plan_file: plan.out
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
