---
- name: Install linkerd CLI
  shell: curl -sL https://run.linkerd.io/install | sh
- name: Create linkerd namespace
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: linkerd
  environment:
    KUBECONFIG: ~/kubeconfig
- name: Create Linkerd Certificate
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: linkerd-identity-issuer
        namespace: linkerd
      spec:
        secretName: linkerd-identity-issuer
        duration: 48h
        renewBefore: 25h
        issuerRef:
          name: cluster-issuer
          kind: ClusterIssuer
        commonName: identity.linkerd.cluster.local
        dnsNames:
        - identity.linkerd.cluster.local
        isCA: true
        privateKey:
          algorithm: ECDSA
        usages:
        - cert sign
        - crl sign
        - server auth
        - client auth
  environment:
    KUBECONFIG: ~/kubeconfig
  notify:
    - init_linkerd
- name: Flush handlers
  meta: flush_handlers
- name: Wait for linkerd to initialize
  pause: minutes=3
