---
- name: Install linkerd
  shell: curl -sL https://run.linkerd.io/install | sh
- name: Install certificate
  block:
    - file:
        path: "/home/{{ ansible_user }}/terraform/mesh"
        mode: 0755
        state: directory
    - copy:
        dest: "/home/{{ ansible_user }}/terraform/mesh/{{ item }}"
        src: "{{ item }}"
      with_items:
        - terraform.tf
        - linkerd.tf
    - stat: path="terraform/mesh/.terraform"
      register: terraform_initialized
    - shell:
        cmd: terraform init
        chdir: "terraform/mesh"
      when: terraform_initialized.stat.exists == false
    - name: Plan deployment
      terraform:
        project_path: "terraform/mesh" # required. The path to the root of the Terraform directory with the vars.tf/main.tf/etc to use.
        state: planned # not required. choices: planned;present;absent. Goal state of given stage/project
        plan_file: plan.out
    - name: Apply deployment
      terraform:
        project_path: "terraform/mesh" # required. The path to the root of the Terraform directory with the vars.tf/main.tf/etc to use.
        state: present # not required. choices: planned;present;absent. Goal state of given stage/project
        plan_file: plan.out
      notify:
        - init_linkerd
  environment:
    KUBECONFIG: ~/kubeconfig
