---
- name: Initialize Elastic Logging Cluster
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
  block:
    - community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: elasticsearch.k8s.elastic.co/v1
          kind: Elasticsearch
          metadata:
            name: index
            namespace: logging
          spec:
              version: 7.5.0
              http:
                tls:
                  selfSignedCertificate:
                    disabled: true
              nodeSets:
                - name: default
                  count: 1
                  config:
                    node.master: true
                    node.data: true
                    node.ingest: true
                    node.store.allow_mmap: false
                  volumeClaimTemplates:
                    - metadata:
                        name: index-data
                      spec:
                        accessModes:
                          - ReadWriteOnce
                        resources:
                          requests:
                            storage: 1Ti
                        storageClassName: nfs-client
                  podTemplate:
                    metadata:
                      annotations:
                        linkerd.io/inject: enabled
                    spec:
                      automountServiceAccountToken: true
    # - name: Wait for Elasticsearch to Start
    #   pause: minutes=5
    - community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: logging.banzaicloud.io/v1beta1
          kind: ClusterOutput
          metadata:
            name: logging-index-output
            namespace: logging
          spec:
            elasticsearch:
              host: index-es-http.logging.svc.cluster.local
              port: 9200
              scheme: http
              user: elastic
              password:
                valueFrom:
                  secretKeyRef:
                    name: index-es-elastic-user
                    key: elastic
              buffer:
                timekey: 1m
                timekey_wait: 30s
                timekey_use_utc: true
