---
- name: Create project folder
  file:
    path: "/home/{{ ansible_user }}/terraform/logging"
    state: directory
    mode: 0755
- name: Deploy logging apparatus
  block:
    - name: Deploy namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: monitoring
            annotations:
              linkerd.io/inject: enabled
    - name: Deploy alertManager
      import_tasks: alertmanager.yml
    - name: Deploy logging
      import_tasks: logging.yml
    - name: Set up Loki output
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: logging.banzaicloud.io/v1beta1
          kind: ClusterOutput
          metadata:
            name: logging-index-output
            namespace: logging
          spec:
            loki:
              url: http://loki.monitoring:3100
              configure_kubernetes_labels: true
              buffer:
                timekey: 1m
                timekey_wait: 30s
                timekey_use_utc: true
    - name: Linkerd viz namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: linkerd-viz
            annotations:
              linkerd.io/inject: enabled
    - name: Deploy Linkerd-viz
      kubernetes.core.helm:
        wait: true
        chart_ref: linkerd-viz
        name: linkerd-viz
        # According to Linkerd documentation, separate Grafana is only supported in edge
        # The feature will be enabled in the upcoming linkerd release 2.12
        # https://linkerd.io/2.11/tasks/grafana/
        chart_repo_url: https://helm.linkerd.io/edge
        release_namespace: linkerd-viz
        release_values:
          jaegerUrl: jaeger.linkerd-jaeger:16686
          prometheusUrl: http://metrics-kube-prometheus-st-prometheus.monitoring:9090
          grafanaUrl: 'metrics-grafana.monitoring:80'
          # Since we're bringing our own Prometheus and Grafana instances,
          # We have to disable linkerd's Grafana and Prometheus instances
          prometheus:
            enabled: false
          grafana:
            enabled: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
    KUBE_CONFIG_PATH: "/home/{{ ansible_user }}/kubeconfig"