---
- name: Create project folder
  file:
    path: "/home/{{ ansible_user }}/terraform/vault"
    state: directory
    mode: 0755
- name: Deploy Vault Operator
  block:
    - copy: src="{{ item }}" dest="/home/{{ ansible_user }}/terraform/vault/{{ item }}"
      with_items:
      - vault.tf
      - terraform.tf
    - stat:
        path: "terraform/vault/.terraform"
      register: terraform_initialized
    - shell:
        cmd: terraform init
        chdir: "terraform/vault"
      when: terraform_initialized.stat.exists != true
    - name: Plan Deployment
      terraform:
        project_path: terraform/vault
        state: planned
        plan_file: plan.out
    - name: Apply Deployment
      terraform:
        project_path: terraform/vault
        state: present
        plan_file: plan.out
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
    KUBE_CONFIG_PATH: "/home/{{ ansible_user }}/kubeconfig"
- import_tasks: vault.yml
- import_tasks: monitoring.yml
- name: Get certificate from secret
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
    KUBE_CONFIG_PATH: "/home/{{ ansible_user }}/kubeconfig"
  shell: "kubectl get secret -n vault-system vault-tls -o jsonpath=\"{.data.ca\\.crt}\" | base64 --decode > /home/{{ ansible_user }}/vault.crt"
- name: Set up Vault
  become: yes
  apk: name=vault state=present