---
- name: Create project folder
  file:
    path: "/home/{{ ansible_user }}/terraform/vault"
    state: directory
    mode: 0755
- name: Deploy Vault Operator
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
    KUBE_CONFIG_PATH: "/home/{{ ansible_user }}/kubeconfig"
  block:
    - name: Deploy Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: vault-system
            annotations:
              linkerd.io/inject: enabled
    - name: Deploy Operator chart
      kubernetes.core.helm:
        wait: true
        chart_ref: vault-operator
        name: vault-operator
        chart_repo_url: https://kubernetes-charts.banzaicloud.com
        release_namespace: vault-system
    - name: Deploy Webhook chart
      kubernetes.core.helm:
        wait: true
        chart_ref: vault-secrets-webhook
        name: vault-secrets-webhook
        chart_repo_url: https://kubernetes-charts.banzaicloud.com
        release_namespace: vault-system
        release_values:
          certificate:
            generate: false
            useCertManager: true
          image:
            tag: 1.15.2
- import_tasks: vault.yml
- import_tasks: monitoring.yml
- name: Get certificate from secret
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
    KUBE_CONFIG_PATH: "/home/{{ ansible_user }}/kubeconfig"
  shell: "kubectl get secret -n vault-system vault-tls -o jsonpath=\"{.data.ca\\.crt}\" | base64 --decode > /home/{{ ansible_user }}/vault.crt"
- name: Set up Vault
  apt: name=vault state=present
  become: yes