---
- name: Create elastic release
  block:
    - kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: elastic-system
            annotations:
              linkerd.io/inject: enabled
    - kubernetes.core.helm:
        chart_repo_url: https://helm.elastic.co
        chart_ref: eck-operator
        release_name: elastic-operator
        release_namespace: elastic-system
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
