---
- name: Create project folder
  file:
    path: "/home/{{ ansible_user }}/terraform/elastic"
    state: directory
    mode: 0755
- name: Deploy Elasticsearch
  shell:
    cmd: "/home/{{ansible_user}}/.linkerd2/bin/linkerd inject https://download.elastic.co/downloads/eck/{{ eck_version }}/all-in-one.yaml | kubectl apply -f -"
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
