---
- name: Deploy NFS Client
  block:
    - kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: nfs
            annotations:
              linkerd.io/inject: enabled
    - kubernetes.core.helm:
        name: nfs-client
        # Deprecation notice - https://artifacthub.io/packages/helm/ckotzbauer/nfs-client-provisioner
        # This change updates the repo and chart name to match
        chart_ref: nfs-subdir-external-provisioner
        chart_repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
        release_namespace: nfs
        values:
          nfs:
            server: 192.168.0.120
            path: /mnt/external
            mountOptions:
              - nfsvers=4
              - async
              - noatime
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
