---
- name: Create project folder
  file:
    path: "/home/{{ ansible_user }}/terraform/nas"
    state: directory
    mode: 0755
- name: Deploy NFS Client
  block:
    - copy: src="{{ item }}" dest="/home/{{ ansible_user }}/terraform/nas/{{ item }}"
      with_items:
      - nas.tf
      - terraform.tf
    - stat:
        path: "terraform/nas/.terraform"
      register: terraform_initialized
    - shell:
        cmd: terraform init
        chdir: "terraform/nas"
      when: terraform_initialized.stat.exists != true
    - name: Plan Deployment
      terraform:
        project_path: terraform/nas
        state: planned
        plan_file: plan.out
    - name: Apply Deployment
      terraform:
        project_path: terraform/nas
        state: present
        plan_file: plan.out
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
