---
- name: Deploy NFS Client
  block:
    - kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: nfs
            annotations:
              linkerd.io/inject: enabled
    - kubernetes.core.helm:
        name: nfs-client
        chart_ref: nfs-client-provisioner
        chart_repo_url: https://ckotzbauer.github.io/helm-charts
        release_namespace: nfs
        values:
          nfs:
            server: 192.168.0.120
            path: /mnt/external
            mountOptions:
              - nfsvers=3
              - async
              - noatime
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
