---
- name: Create Logging resource
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: logging.banzaicloud.io/v1beta1
      kind: Logging
      metadata:
        name: files-logger
        namespace: files
      spec:
        fluentd: {}
        fluentbit: {}
        controlNamespace: logging
- name: Create Flow resource
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: logging.banzaicloud.io/v1beta1
      kind: Flow
      metadata:
        name: files-flow
        namespace: files
      spec:
        globalOutputRefs:
        - logging-index-output
        filters:
          - tag_normaliser: {}
          - parser:
              remove_key_name_field: true
              reserve_data: true
              parse:
                type: multi_format
                patterns:
                  - format: regexp
                    expression: '/^(?<time>[^\]]*) \[(?<level>[^ ]*)\] (?<source>[^\":]*): (?<message>.*)$/'
                    time_key: logtime
                    time_format: '%Y-%m-%dT%H:%M:%S.%LZ'
                  - format: regexp
                    expression: '/^time="(?<time>[^\]]*)" level=(?<level>[^ ]*) msg="(?<message>[^\"]*)"/'
                    time_key: time
                    time_format: '%Y-%m-%dT%H:%M:%SZ'
                  - format: regexp
                    expression: '/^level=(?<level>[^ ]*) ts=(?<time>[^\]]*) caller=(?<source>.*) msg="(?<message>[^\"]*)"/'
                    time_key: time
                    time_format: '%Y-%m-%dT%H:%M:%S.%LZ'
                  - format: regexp
                    expression: '^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$'
                    time_key: time
                    time_format: '%d/%b/%Y:%H:%M:%S %z'
        match:
        - select:
            labels:
              app: owncloud